# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GOST', models.CharField(db_index=True, max_length=30, verbose_name='ГОСТ')),
                ('material', models.CharField(choices=[('Углеродистая сталь', 'Углеродистая сталь'), ('СТ 10', 'СТ 10'), ('СТ 20', 'СТ 20'), ('СТ 35', 'СТ 35'), ('СТ 45', 'СТ 45'), ('СТ 20С', 'СТ 20С'), ('СТ 20А', 'СТ 20А'), ('СТ 20КТ', 'СТ 20ФА'), ('СТ 13ХФА', 'СТ 13ХФА'), ('СТ 09Г2С', 'СТ 09Г2С'), ('СТ 12Х1МФ', 'СТ 12Х1МФ'), ('СТ 15Х5М', 'СТ 15Х5М'), ('04X18H10', '04X18H10'), ('06XH28MДT', '06XH28MДT'), ('08X13', '08X13'), ('08X17T', '08X17T'), ('08X20H14C2', '08X20H14C2'), ('08X18H10', '08X18H10'), ('08X18H10T', '08X18H10T'), ('08X18H12T', '08X18H12T'), ('08X17H15M3T', '08X17H15M3T'), ('08X22H6T', '08X22H6T'), ('08X18H12Б', '08X18H12Б'), ('10X17H13M2T', '10X17H13M2T'), ('10X23H18', '10X23H18'), ('12X13', '12X13'), ('12X17', '12X17'), ('12X18H10T', '12X18H10T'), ('12X18H12T', '12X18H12T'), ('12X18H9', '12X18H9'), ('15X25T', '15X25T'), ('17X18H9', '17X18H9'), ('Дюралюминий', 'Дюралюминий'), ('Титан', 'Титан'), ('Медь', 'Медь'), ('Латунь', 'Латунь'), ('Свинец', 'Свинец'), ('Золото', 'Золото')], db_index=True, default=1, max_length=30, verbose_name='Материал')),
                ('size', models.CharField(db_index=True, default=1, max_length=30, verbose_name='Размер')),
                ('wall_thickness', models.FloatField(verbose_name='Толщина стенки')),
                ('length', models.FloatField(default=1, verbose_name='Длина трубы')),
                ('count', models.IntegerField(default=1, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'труба',
                'verbose_name_plural': 'трубы',
                'ordering': ['GOST'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='pipe',
            unique_together=set([('GOST', 'material', 'wall_thickness', 'size', 'length')]),
        ),
    ]
